# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ae7d1118bdb04c5bb2da96f155f1b9fa38d9f0086dd98a685e41856835c86914780a2bb294f0cd69c93adb5093489c4b37fa615c0118d0cf384fd67ac5a089a

test:
  secret_key_base: b1b35bb716f938ef7c81b0d3b0fe60a041797d29b00fa5239352d1dd6a7fb40bdef98a061489e9a0a7081f39cc1cd8dfb88f69995453de2e46f7b940d056fc3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
